set_property -quiet PACKAGE_PIN AU31 [get_ports {sram0_k_p} ]
set_property -quiet PACKAGE_PIN AU30 [get_ports {sram0_k_n} ]
set_property -quiet PACKAGE_PIN AM24 [get_ports sram0_a[ 0] ]
set_property -quiet PACKAGE_PIN AL24 [get_ports sram0_a[ 1] ]
set_property -quiet PACKAGE_PIN AN21 [get_ports sram0_a[ 2] ]
set_property -quiet PACKAGE_PIN AT24 [get_ports sram0_a[ 3] ]
set_property -quiet PACKAGE_PIN AT23 [get_ports sram0_a[ 4] ]
set_property -quiet PACKAGE_PIN AR23 [get_ports sram0_a[ 5] ]
set_property -quiet PACKAGE_PIN AP23 [get_ports sram0_a[ 6] ]
set_property -quiet PACKAGE_PIN AP24 [get_ports sram0_a[ 7] ]
set_property -quiet PACKAGE_PIN AN24 [get_ports sram0_a[ 8] ]
set_property -quiet PACKAGE_PIN AN23 [get_ports sram0_a[ 9] ]
set_property -quiet PACKAGE_PIN AN22 [get_ports sram0_a[10] ]
set_property -quiet PACKAGE_PIN AT25 [get_ports sram0_a[11] ]
set_property -quiet PACKAGE_PIN AR25 [get_ports sram0_a[12] ]
set_property -quiet PACKAGE_PIN AT22 [get_ports sram0_a[13] ]
set_property -quiet PACKAGE_PIN AR22 [get_ports sram0_a[14] ]
set_property -quiet PACKAGE_PIN AY33 [get_ports sram0_a[15] ]
set_property -quiet PACKAGE_PIN AW33 [get_ports sram0_a[16] ]
set_property -quiet PACKAGE_PIN AW31 [get_ports sram0_a[17] ]
set_property -quiet PACKAGE_PIN AV31 [get_ports sram0_a[18] ]
set_property -quiet PACKAGE_PIN AY30 [get_ports sram0_a[19] ]
set_property -quiet PACKAGE_PIN AW30 [get_ports sram0_a[20] ]
set_property -quiet PACKAGE_PIN AY32 [get_ports sram0_a[21] ]
set_property -quiet PACKAGE_PIN BD33 [get_ports sram0_dq[ 0] ]
set_property -quiet PACKAGE_PIN BC33 [get_ports sram0_dq[ 1] ]
set_property -quiet PACKAGE_PIN BA33 [get_ports sram0_dq[ 2] ]
set_property -quiet PACKAGE_PIN BA32 [get_ports sram0_dq[ 3] ]
set_property -quiet PACKAGE_PIN BC32 [get_ports sram0_dq[ 4] ]
set_property -quiet PACKAGE_PIN BC31 [get_ports sram0_dq[ 5] ]
set_property -quiet PACKAGE_PIN BD31 [get_ports sram0_dq[ 6] ]
set_property -quiet PACKAGE_PIN BD30 [get_ports sram0_dq[ 7] ]
set_property -quiet PACKAGE_PIN BB30 [get_ports sram0_dq[ 8] ]
set_property -quiet PACKAGE_PIN BB32 [get_ports sram0_dq[ 9] ]
set_property -quiet PACKAGE_PIN BB31 [get_ports sram0_dq[10] ]
set_property -quiet PACKAGE_PIN AJ24 [get_ports sram0_dq[11] ]
set_property -quiet PACKAGE_PIN AJ23 [get_ports sram0_dq[12] ]
set_property -quiet PACKAGE_PIN AM22 [get_ports sram0_dq[13] ]
set_property -quiet PACKAGE_PIN AL22 [get_ports sram0_dq[14] ]
set_property -quiet PACKAGE_PIN AK22 [get_ports sram0_dq[15] ]
set_property -quiet PACKAGE_PIN AK21 [get_ports sram0_dq[16] ]
set_property -quiet PACKAGE_PIN AL23 [get_ports sram0_dq[17] ]
set_property -quiet PACKAGE_PIN BA30 [get_ports sram0_bws_n[0] ]
set_property -quiet PACKAGE_PIN AK23 [get_ports sram0_bws_n[1] ]
set_property -quiet PACKAGE_PIN AY31 [get_ports {sram0_rnw} ]
set_property -quiet PACKAGE_PIN AU32 [get_ports {sram0_ld_n} ]
set_property -quiet PACKAGE_PIN AV32 [get_ports {sram0_doff_n} ]

set_property -quiet PACKAGE_PIN AR31 [get_ports {sram1_k_p} ]
set_property -quiet PACKAGE_PIN AP31 [get_ports {sram1_k_n} ]
set_property -quiet PACKAGE_PIN AW24 [get_ports sram1_a[ 0] ]
set_property -quiet PACKAGE_PIN AV24 [get_ports sram1_a[ 1] ]
set_property -quiet PACKAGE_PIN AV22 [get_ports sram1_a[ 2] ]
set_property -quiet PACKAGE_PIN BA23 [get_ports sram1_a[ 3] ]
set_property -quiet PACKAGE_PIN BA22 [get_ports sram1_a[ 4] ]
set_property -quiet PACKAGE_PIN BC24 [get_ports sram1_a[ 5] ]
set_property -quiet PACKAGE_PIN BB24 [get_ports sram1_a[ 6] ]
set_property -quiet PACKAGE_PIN BD23 [get_ports sram1_a[ 7] ]
set_property -quiet PACKAGE_PIN BC23 [get_ports sram1_a[ 8] ]
set_property -quiet PACKAGE_PIN BC22 [get_ports sram1_a[ 9] ]
set_property -quiet PACKAGE_PIN BB22 [get_ports sram1_a[10] ]
set_property -quiet PACKAGE_PIN BB25 [get_ports sram1_a[11] ]
set_property -quiet PACKAGE_PIN BA24 [get_ports sram1_a[12] ]
set_property -quiet PACKAGE_PIN BD25 [get_ports sram1_a[13] ]
set_property -quiet PACKAGE_PIN BD24 [get_ports sram1_a[14] ]
set_property -quiet PACKAGE_PIN AP33 [get_ports sram1_a[15] ]
set_property -quiet PACKAGE_PIN AN33 [get_ports sram1_a[16] ]
set_property -quiet PACKAGE_PIN AP30 [get_ports sram1_a[17] ]
set_property -quiet PACKAGE_PIN AP29 [get_ports sram1_a[18] ]
set_property -quiet PACKAGE_PIN AT30 [get_ports sram1_a[19] ]
set_property -quiet PACKAGE_PIN AR30 [get_ports sram1_a[20] ]
set_property -quiet PACKAGE_PIN AT33 [get_ports sram1_a[21] ]
set_property -quiet PACKAGE_PIN AM32 [get_ports sram1_dq[ 0] ]
set_property -quiet PACKAGE_PIN AL32 [get_ports sram1_dq[ 1] ]
set_property -quiet PACKAGE_PIN AL30 [get_ports sram1_dq[ 2] ]
set_property -quiet PACKAGE_PIN AL29 [get_ports sram1_dq[ 3] ]
set_property -quiet PACKAGE_PIN AM31 [get_ports sram1_dq[ 4] ]
set_property -quiet PACKAGE_PIN AM30 [get_ports sram1_dq[ 5] ]
set_property -quiet PACKAGE_PIN AN32 [get_ports sram1_dq[ 6] ]
set_property -quiet PACKAGE_PIN AN31 [get_ports sram1_dq[ 7] ]
set_property -quiet PACKAGE_PIN AN29 [get_ports sram1_dq[ 8] ]
set_property -quiet PACKAGE_PIN AK31 [get_ports sram1_dq[ 9] ]
set_property -quiet PACKAGE_PIN AK30 [get_ports sram1_dq[10] ]
set_property -quiet PACKAGE_PIN AW23 [get_ports sram1_dq[11] ]
set_property -quiet PACKAGE_PIN AV23 [get_ports sram1_dq[12] ]
set_property -quiet PACKAGE_PIN AY23 [get_ports sram1_dq[13] ]
set_property -quiet PACKAGE_PIN AY22 [get_ports sram1_dq[14] ]
set_property -quiet PACKAGE_PIN BA25 [get_ports sram1_dq[15] ]
set_property -quiet PACKAGE_PIN AY25 [get_ports sram1_dq[16] ]
set_property -quiet PACKAGE_PIN AU25 [get_ports sram1_dq[17] ]
set_property -quiet PACKAGE_PIN AM29 [get_ports sram1_bws_n[0] ]
set_property -quiet PACKAGE_PIN AU24 [get_ports sram1_bws_n[1] ]
set_property -quiet PACKAGE_PIN AR33 [get_ports {sram1_rnw} ]
set_property -quiet PACKAGE_PIN AR32 [get_ports {sram1_ld_n} ]
set_property -quiet PACKAGE_PIN AT32 [get_ports {sram1_doff_n} ]

set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram0_k_p} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram0_k_n} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports sram0_a[*] ]
set_property -quiet IOSTANDARD HSTL_II [get_ports sram0_dq[*] ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports sram0_bws_n[*] ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram0_rnw} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram0_ld_n} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram0_doff_n} ]

set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram1_k_p} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram1_k_n} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports sram1_a[*] ]
set_property -quiet IOSTANDARD HSTL_II [get_ports sram1_dq[*] ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports sram1_bws_n[*] ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram1_rnw} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram1_ld_n} ]
set_property -quiet IOSTANDARD HSTL_I  [get_ports {sram1_doff_n} ]

set_property INTERNAL_VREF {0.75} [get_iobanks 36]
set_property INTERNAL_VREF {0.75} [get_iobanks 35]
set_property INTERNAL_VREF {0.75} [get_iobanks 34]
